# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 09:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_blogpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='research',
        ),
        migrations.AddField(
            model_name='homepage',
            name='IV_CML',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tools_dbs',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
