# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0007_testpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestPage',
            new_name='ToolsDBsPage',
        ),
    ]
