# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('lvl', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=100)),
                ('url', models.TextField(editable=False)),
                ('lwst_level', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ExioVisuals.Country')),
            ],
            options={
                'verbose_name_plural': 'FancyTreeCountry',
                'ordering': ('tree_id', 'lft'),
            },
        ),
        migrations.CreateModel(
            name='GhgEmissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(max_length=128, unique=True)),
                ('absolute', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('local', models.CharField(default='none', max_length=200)),
                ('lvl', models.CharField(default='none', max_length=200)),
                ('slug', models.CharField(max_length=100)),
                ('url', models.TextField(editable=False)),
                ('lwst_level', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ExioVisuals.Product')),
            ],
            options={
                'verbose_name_plural': 'FancyTreeProduct',
                'ordering': ('tree_id', 'lft'),
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='ExioVisuals.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Selection2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ManyToManyField(to='ExioVisuals.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Selection3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Selection4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=100)),
                ('url', models.TextField(editable=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ExioVisuals.Substance')),
            ],
            options={
                'verbose_name_plural': 'FancyTreeSubstance',
                'ordering': ('tree_id', 'lft'),
            },
        ),
        migrations.CreateModel(
            name='YearF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=100)),
                ('url', models.TextField(editable=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ExioVisuals.YearF')),
            ],
            options={
                'verbose_name_plural': 'FancyTreeYearF',
                'ordering': ('tree_id', 'lft'),
            },
        ),
        migrations.CreateModel(
            name='years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='selection4',
            name='yearF',
            field=models.ManyToManyField(to='ExioVisuals.YearF'),
        ),
        migrations.AddField(
            model_name='selection3',
            name='substances',
            field=models.ManyToManyField(to='ExioVisuals.Substance'),
        ),
        migrations.AlterUniqueTogether(
            name='yearf',
            unique_together=set([('name', 'slug', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='substance',
            unique_together=set([('name', 'slug', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('name', 'slug', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together=set([('name', 'slug', 'parent')]),
        ),
    ]
